name: CI Workflow
on: 
  push:
    branches:
      - 'main'
jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Maven Compile/Test/Package
        run: mvn --active-profiles prod package
