name: CI Workflow
on: 
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Maven Compile/Test/Package
        run: mvn --activate-profiles prod package
      - name: Teste
        run: mvn test
  segundo-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Teste Package
          run: mvn package -DskipTests
      
